[package]
name = "instancifier"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["cdylib"]
[dependencies]
shared_memory = "0.12"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
sysinfo = "0.33"
once_cell = "1.8"
simplelog = "0.12"
log = "0.4"
named-lock = "0.4"

