name: Rust Build and Release
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose --release

    - name: Upload Linux Artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: linux-artifacts
        path: target/release/libinstancifier.so

    - name: Upload Windows Artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifacts
        path: |
          target/release/instancifier.dll
          target/release/instancifier.pdb

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:  # Add permissions block
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/download-artifact@v4
      with:
        name: linux-artifacts
        path: linux
    
    - uses: actions/download-artifact@v4
      with:
        name: windows-artifacts
        path: windows

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${GITHUB_REF#refs/tags/}" \
          --title "${GITHUB_REF#refs/tags/}" \
          --notes "Release ${GITHUB_REF#refs/tags/}" \
          linux/libinstancifier.so \
          windows/instancifier.dll \
          windows/instancifier.pdb
